"""create decisions table

Revision ID: c336f4676776
Revises: 01197671c9e2
Create Date: 2026-05-08 12:02:07.460386

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c336f4676776"
down_revision: str | Sequence[str] | None = "01197671c9e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decisions",
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("conditions_json", sa.JSON(), nullable=False),
        sa.Column("rationale_html", sa.String(), nullable=False),
        sa.Column("committed_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sealed_ledger_entry_id", sa.String(length=32), nullable=True),
        sa.Column("committed_ledger_entry_id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_index("ix_decisions_case_id", "decisions", ["case_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_decisions_case_id", table_name="decisions")
    op.drop_table("decisions")
    # ### end Alembic commands ###
