// Hand-authored TypeScript shadow of `contracts.users.User` (Story 1.4).
// TODO(story-2-11): replace with the type generated by `make contracts`.

export type Role = 'analyst' | 'team_lead' | 'regulator';

export interface User {
  id: string;
  name: string;
  role: Role;
  initials: string;
}

// Pinned UUIDs — mirror of contracts.users module constants.
// .env.example carries the same values for any consumer that wants overrides.
export const ANALYST_ID = 'dc2aaaa3-555b-4636-89d0-6047dc205220';
export const TEAM_LEAD_ID = 'a725a9bb-5b8e-4984-8d23-19c682225002';
export const REGULATOR_ID = 'a1582a20-62e1-497b-910c-45c0b0ee7030';

export const DEMO_USERS: readonly User[] = [
  { id: ANALYST_ID, name: 'Kamal Singh', role: 'analyst', initials: 'KS' },
  { id: TEAM_LEAD_ID, name: 'Rohan Mehta', role: 'team_lead', initials: 'RM' },
  { id: REGULATOR_ID, name: 'Anika Iyer', role: 'regulator', initials: 'AI' },
] as const;
