"""Pydantic source-of-truth contracts shared across cockpit-api and agents."""

from __future__ import annotations

from contracts.agent_action import (
    AgentActionLedgerEntry,
    ErrorInfo,
    PromptHash,
)
from contracts.agent_mesh import (
    AGENT_RENDER_ORDER,
    AgentMeshAgentEntry,
    AgentMeshAgentState,
    AgentMeshSnapshot,
    AgentSlug,
)
from contracts.case_supervisor import CaseIntakeOutcome
from contracts.cases import (
    ALLOWED_TRANSITIONS,
    ANANYA_IYER_ID,
    SHREE_VENKAT_ID,
    VORA_CAPITAL_ID,
    Case,
    CaseId,
    CaseLatestDecision,
    CaseState,
    CaseStateTransitionError,
    CustomerMetadata,
    assert_transition,
    get_demo_case_fixtures,
    is_valid_case_id,
)
from contracts.confidence import THRESHOLDS, ConfidenceBand, to_band
from contracts.decision import (
    CommitDecisionRequest,
    CommitDecisionResponse,
    Decision,
    DecisionOutcome,
)
from contracts.document_intelligence import (
    DocumentIntelligenceInput,
    DocumentIntelligenceOutput,
    ExtractedField,
    FieldValue,
)
from contracts.entity_verification import (
    EntityVerificationInput,
    EntityVerificationResult,
    FieldMismatch,
)
from contracts.learning_event import (
    CorrectionTag,
    LearningEventInput,
    LearningEventLedgerPayload,
    LearningEventResponse,
)
from contracts.ledger import (
    ActorType,
    CockpitChatToolLedgerPayload,
    DecisionSealedPayload,
    LedgerEntry,
    LedgerEntryId,
    OfficerDecisionCommittedPayload,
    OfficerDecisionUndonePayload,
    is_valid_ledger_entry_id,
)
from contracts.mca import (
    MCACompanyMaster,
    MCADirector,
    MCAShareholder,
    MCAStatus,
)
from contracts.provenance import Provenance, ProvenancedField
from contracts.reasoning_trace import (
    ConfidenceWithRationale,
    IncompleteReasoningTraceError,
    ReasoningTrace,
)
from contracts.risk import (
    RiskBand,
    RiskComponent,
    RiskComponentName,
    RiskScore,
    RiskScoringInput,
)
from contracts.screening import (
    HitDisposition,
    ScreeningAdapter,
    ScreeningAgentInput,
    ScreeningAgentOutput,
    ScreeningCategory,
    ScreeningHit,
    ScreeningPermanentError,
    ScreeningRequest,
    ScreeningSubject,
    ScreeningTemporaryError,
)
from contracts.sse import SseEvent
from contracts.ubo import (
    EdgeKind,
    NomineeFlag,
    UBOEdge,
    UBOEntityNode,
    UBOGraph,
    UBOGraphInput,
    UBONode,
    UBONodeId,
    UBOPersonNode,
)
from contracts.users import (
    ANALYST_ID,
    DEMO_USERS,
    REGULATOR_ID,
    TEAM_LEAD_ID,
    Role,
    User,
    find_user_by_id,
)
from contracts.writing import (
    CitedClaim,
    DraftedRationale,
    WritingAgentInput,
)

__all__ = [
    "AGENT_RENDER_ORDER",
    "ALLOWED_TRANSITIONS",
    "ANALYST_ID",
    "ANANYA_IYER_ID",
    "ActorType",
    "AgentActionLedgerEntry",
    "AgentMeshAgentEntry",
    "AgentMeshAgentState",
    "AgentMeshSnapshot",
    "AgentSlug",
    "Case",
    "CaseId",
    "CaseIntakeOutcome",
    "CaseLatestDecision",
    "CommitDecisionRequest",
    "CommitDecisionResponse",
    "Decision",
    "DecisionOutcome",
    "DecisionSealedPayload",
    "OfficerDecisionCommittedPayload",
    "CockpitChatToolLedgerPayload",
    "CaseState",
    "CaseStateTransitionError",
    "ConfidenceBand",
    "CitedClaim",
    "ConfidenceWithRationale",
    "CorrectionTag",
    "CustomerMetadata",
    "DEMO_USERS",
    "DocumentIntelligenceInput",
    "DocumentIntelligenceOutput",
    "DraftedRationale",
    "EdgeKind",
    "EntityVerificationInput",
    "EntityVerificationResult",
    "ErrorInfo",
    "ExtractedField",
    "FieldMismatch",
    "FieldValue",
    "HitDisposition",
    "IncompleteReasoningTraceError",
    "LearningEventInput",
    "LearningEventLedgerPayload",
    "LearningEventResponse",
    "LedgerEntry",
    "LedgerEntryId",
    "MCACompanyMaster",
    "MCADirector",
    "MCAShareholder",
    "MCAStatus",
    "NomineeFlag",
    "OfficerDecisionUndonePayload",
    "PromptHash",
    "Provenance",
    "ProvenancedField",
    "REGULATOR_ID",
    "ReasoningTrace",
    "RiskBand",
    "RiskComponent",
    "RiskComponentName",
    "RiskScore",
    "RiskScoringInput",
    "Role",
    "SHREE_VENKAT_ID",
    "ScreeningAdapter",
    "ScreeningAgentInput",
    "ScreeningAgentOutput",
    "ScreeningCategory",
    "ScreeningHit",
    "ScreeningPermanentError",
    "ScreeningRequest",
    "ScreeningSubject",
    "ScreeningTemporaryError",
    "SseEvent",
    "TEAM_LEAD_ID",
    "THRESHOLDS",
    "UBOEdge",
    "UBOEntityNode",
    "UBOGraph",
    "UBOGraphInput",
    "UBONode",
    "UBONodeId",
    "UBOPersonNode",
    "User",
    "VORA_CAPITAL_ID",
    "WritingAgentInput",
    "assert_transition",
    "find_user_by_id",
    "get_demo_case_fixtures",
    "is_valid_case_id",
    "is_valid_ledger_entry_id",
    "to_band",
]
