/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/agents/document_intelligence/extract': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run the Document Intelligence agent against a case's documents
     * @description Calls the Document Intelligence agent with the supplied case id and document refs. Returns the extracted fields with provenance + confidence band. Every invocation writes one ledger entry.
     */
    post: operations['extract_document_fields_v1_agents_document_intelligence_extract_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/cases': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List cases (newest first) */
    get: operations['list_cases_v1_cases_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/cases/{case_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single case by ID */
    get: operations['get_case_v1_cases__case_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/cases/{case_id}/intake': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run the Case Supervisor intake fan-out for a case
     * @description Triggers Story 3.5's CaseSupervisor for the given case. Fans out across the intake-agent registry (currently: Document Intelligence), persists results, transitions the case to decision_ready on success or escalated on agent failure. Returns a typed CaseIntakeOutcome.
     */
    post: operations['run_case_intake_v1_cases__case_id__intake_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/cases/{case_id}/intake/document_intelligence': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the Document Intelligence agent's intake output for a case
     * @description Returns the typed extraction output produced by Story 3.4's Document Intelligence agent for the given case. 404 if the case doesn't exist OR if intake hasn't run yet — distinguished by the `detail` field of the RFC 7807 problem body.
     */
    get: operations['get_document_intelligence_intake_v1_cases__case_id__intake_document_intelligence_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Me
     * @description Return the user identified by ``X-Cockpit-Demo-User``.
     */
    get: operations['me_v1_users_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CaseEnvelope
     * @description ``Case`` plus the API-shape-only ``_links`` placeholder.
     */
    CaseEnvelope: {
      /** Links */
      _links?: {
        [key: string]: string | null;
      };
      /** Assigned To User Id */
      assigned_to_user_id?: string | null;
      /** Closure Date */
      closure_date?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      customer_metadata: components['schemas']['CustomerMetadata'];
      /** Id */
      id: string;
      /** Risk Band */
      risk_band?: ('low' | 'medium_low' | 'medium_high' | 'high') | null;
      state: components['schemas']['CaseState'];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * CaseIntakeOutcome
     * @description Result envelope for one case-intake supervisor run.
     */
    CaseIntakeOutcome: {
      /** Agents Run */
      agents_run?: string[];
      /** Case Id */
      case_id: string;
      /**
       * Completed At
       * Format: date-time
       */
      completed_at: string;
      /** Error Message */
      error_message?: string | null;
      /** Failed Agent */
      failed_agent?: string | null;
      /**
       * Fields Extracted
       * @default 0
       */
      fields_extracted: number;
      /**
       * Status
       * @enum {string}
       */
      status: 'completed' | 'blocked';
    };
    /**
     * CaseListResponse
     * @description Pagination envelope per ``architecture.md#Format Patterns``.
     */
    CaseListResponse: {
      /**
       * Has More
       * @default false
       */
      has_more: boolean;
      /** Items */
      items: components['schemas']['CaseEnvelope'][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /**
     * CaseState
     * @description Lifecycle states. See ``ALLOWED_TRANSITIONS`` for the edge set.
     * @enum {string}
     */
    CaseState: 'intake_scheduled' | 'decision_ready' | 'committed' | 'escalated' | 'closed';
    /**
     * ConfidenceBand
     * @description Four-tier confidence banding. Wire format is snake_case.
     * @enum {string}
     */
    ConfidenceBand: 'low' | 'medium_low' | 'medium_high' | 'high';
    /**
     * CustomerMetadata
     * @description Customer-side facts attached to a case.
     *
     *     ``extra`` is an extensibility escape hatch so fixtures (Story 2-4) can carry
     *     demo-only fields without schema churn. Production code should prefer named
     *     fields over ``extra`` once the bank-buyer scope revives.
     */
    CustomerMetadata: {
      /** Country */
      country?: string | null;
      /** Customer Name */
      customer_name: string;
      /** Customer Type */
      customer_type?: ('individual' | 'company') | null;
      /** Extra */
      extra?: {
        [key: string]: unknown;
      };
    };
    /** DocumentIntelligenceInput */
    DocumentIntelligenceInput: {
      /** Case Id */
      case_id: string;
      /** Document Refs */
      document_refs: string[];
    };
    /**
     * DocumentIntelligenceOutput
     * @description Aggregate of ExtractedFields across all input document_refs.
     *
     *     Note (Story 3.4 § AC8): ``evidence_ids`` inside each ``ExtractedField.value``
     *     are empty when the agent returns. The supervisor (Story 3-5) back-fills
     *     them with the agent's own ledger-entry ID after ``@agent_action`` writes
     *     the entry.
     */
    DocumentIntelligenceOutput: {
      /** Case Id */
      case_id: string;
      /** Extracted Fields */
      extracted_fields?: components['schemas']['ExtractedField'][];
    };
    /** ExtractedField */
    ExtractedField: {
      /** Document Ref */
      document_ref: string;
      /** Field Name */
      field_name: string;
      value: components['schemas']['ProvenancedField_Union_str__int__float__bool__NoneType__'];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * Provenance
     * @description Per-datum provenance metadata.
     */
    Provenance: {
      /**
       * Captured At
       * Format: date-time
       */
      captured_at: string;
      /** Confidence */
      confidence: number;
      confidence_band: components['schemas']['ConfidenceBand'];
      /** Evidence Ids */
      evidence_ids?: string[];
      /** Source Agent */
      source_agent: string;
      /** Source System */
      source_system: string;
    };
    /** ProvenancedField[Union[str, int, float, bool, NoneType]] */
    ProvenancedField_Union_str__int__float__bool__NoneType__: {
      provenance: components['schemas']['Provenance'];
      /** Value */
      value: string | number | boolean | null;
    };
    /**
     * Role
     * @description Three demo roles. Wire format is snake_case per architecture.md#Naming Patterns.
     * @enum {string}
     */
    Role: 'analyst' | 'team_lead' | 'regulator';
    /**
     * User
     * @description A demo user. Identity-only — no auth, no permissions, no tenant.
     */
    User: {
      /** Id */
      id: string;
      /** Initials */
      initials: string;
      /** Name */
      name: string;
      role: components['schemas']['Role'];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  extract_document_fields_v1_agents_document_intelligence_extract_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DocumentIntelligenceInput'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentIntelligenceOutput'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_cases_v1_cases_get: {
    parameters: {
      query?: never;
      header?: {
        'X-Cockpit-Demo-User'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CaseListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_case_v1_cases__case_id__get: {
    parameters: {
      query?: never;
      header?: {
        'X-Cockpit-Demo-User'?: string | null;
      };
      path: {
        /** @description Case ID (`case_<ULID>`) */
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CaseEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  run_case_intake_v1_cases__case_id__intake_post: {
    parameters: {
      query?: never;
      header?: {
        'X-Cockpit-Demo-User'?: string | null;
      };
      path: {
        /** @description Case ID (`case_<ULID>`) */
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CaseIntakeOutcome'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_document_intelligence_intake_v1_cases__case_id__intake_document_intelligence_get: {
    parameters: {
      query?: never;
      header?: {
        'X-Cockpit-Demo-User'?: string | null;
      };
      path: {
        /** @description Case ID (`case_<ULID>`) */
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentIntelligenceOutput'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  me_v1_users_me_get: {
    parameters: {
      query?: never;
      header?: {
        'X-Cockpit-Demo-User'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
